
spring:
  application:
    name: demo
  data:
    mongodb:
      uri: ${MONGODB_URI}
    auto-index-creation: true

server:
  port: ${PORT:8080}

# JWT configuration
security:
  jwt:
    # Base64-encoded 256-bit (32-byte) secret. Example generated via: openssl rand -base64 32
    secret: ${JWT_SECRET_BASE64}
    # Token lifetime in milliseconds (default 1 hour)
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}